server:
  port: 8888
spring:
  application:
    name: config.server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/48-iq/social-network-config
          default-label: main
          search-paths: "{application}"